### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by warisamin25** [NVlabs/ocropus3#3]
The stack trace for the error https://pastebin.com/zdSF7j36 .
This happens when I run the command "_!ocrobin-pred pages.tgz bin.tgz_" in _das2018-tutorial/30-full-pipeline.ipynb_

**Comment by tmbdev** [comment]
OCRopus3 is being replaced by OCRopus4, which is a rewrite using PyTorch 1.7; release should be soonish.

Please look on github.com/tmbdev/ocropus
